
l= "quarterlyTotalAssets,trailingTotalAssets,quarterlyStockholdersEquity,trailingStockholdersEquity,quarterlyGainsLossesNotAffectingRetainedEarnings,trailingGainsLossesNotAffectingRetainedEarnings,quarterlyRetainedEarnings,trailingRetainedEarnings,quarterlyCapitalStock,trailingCapitalStock,quarterlyTotalLiabilitiesNetMinorityInterest,trailingTotalLiabilitiesNetMinorityInterest,quarterlyTotalNonCurrentLiabilitiesNetMinorityInterest,trailingTotalNonCurrentLiabilitiesNetMinorityInterest,quarterlyOtherNonCurrentLiabilities,trailingOtherNonCurrentLiabilities,quarterlyNonCurrentDeferredRevenue,trailingNonCurrentDeferredRevenue,quarterlyNonCurrentDeferredTaxesLiabilities,trailingNonCurrentDeferredTaxesLiabilities,quarterlyLongTermDebt,trailingLongTermDebt,quarterlyCurrentLiabilities,trailingCurrentLiabilities,quarterlyOtherCurrentLiabilities,trailingOtherCurrentLiabilities,quarterlyCurrentDeferredRevenue,trailingCurrentDeferredRevenue,quarterlyCurrentAccruedExpenses,trailingCurrentAccruedExpenses,quarterlyIncomeTaxPayable,trailingIncomeTaxPayable,quarterlyAccountsPayable,trailingAccountsPayable,quarterlyCurrentDebt,trailingCurrentDebt,quarterlyTotalNonCurrentAssets,trailingTotalNonCurrentAssets,quarterlyOtherNonCurrentAssets,trailingOtherNonCurrentAssets,quarterlyOtherIntangibleAssets,trailingOtherIntangibleAssets,quarterlyGoodwill,trailingGoodwill,quarterlyInvestmentsAndAdvances,trailingInvestmentsAndAdvances,quarterlyNetPPE,trailingNetPPE,quarterlyAccumulatedDepreciation,trailingAccumulatedDepreciation,quarterlyGrossPPE,trailingGrossPPE,quarterlyCurrentAssets,trailingCurrentAssets,quarterlyOtherCurrentAssets,trailingOtherCurrentAssets,quarterlyInventory,trailingInventory,quarterlyAccountsReceivable,trailingAccountsReceivable,quarterlyCashCashEquivalentsAndShortTermInvestments,trailingCashCashEquivalentsAndShortTermInvestments,quarterlyOtherShortTermInvestments,trailingOtherShortTermInvestments,quarterlyCashAndCashEquivalents,trailingCashAndCashEquivalents" 
print(l.split(","))


annual_cash_flow_referer = "https://uk.finance.yahoo.com/quote/TSLA/cash-flow"
annual_cash_flow_url = "https://query1.finance.yahoo.com/ws/fundamentals-timeseries/v1/finance/timeseries/"
annual_cash_flow = ['annualFreeCashFlow', 'trailingFreeCashFlow', 'annualCapitalExpenditure', 'trailingCapitalExpenditure', 'annualOperatingCashFlow', 'trailingOperatingCashFlow', 'annualEndCashPosition', 'trailingEndCashPosition', 'annualBeginningCashPosition', 'trailingBeginningCashPosition', 'annualChangeInCashSupplementalAsReported', 'trailingChangeInCashSupplementalAsReported', 'annualCashFlowFromContinuingFinancingActivities', 'trailingCashFlowFromContinuingFinancingActivities', 'annualNetOtherFinancingCharges', 'trailingNetOtherFinancingCharges', 'annualCashDividendsPaid', 'trailingCashDividendsPaid', 'annualRepurchaseOfCapitalStock', 'trailingRepurchaseOfCapitalStock', 'annualCommonStockIssuance', 'trailingCommonStockIssuance', 'annualRepaymentOfDebt', 'trailingRepaymentOfDebt', 'annualInvestingCashFlow', 'trailingInvestingCashFlow', 'annualNetOtherInvestingChanges', 'trailingNetOtherInvestingChanges', 'annualSaleOfInvestment', 'trailingSaleOfInvestment', 'annualPurchaseOfInvestment', 'trailingPurchaseOfInvestment', 'annualPurchaseOfBusiness', 'trailingPurchaseOfBusiness', 'annualOtherNonCashItems', 'trailingOtherNonCashItems', 'annualChangeInAccountPayable', 'trailingChangeInAccountPayable', 'annualChangeInInventory', 'trailingChangeInInventory', 'annualChangesInAccountReceivables', 'trailingChangesInAccountReceivables', 'annualChangeInWorkingCapital', 'trailingChangeInWorkingCapital', 'annualStockBasedCompensation', 'trailingStockBasedCompensation', 'annualDeferredIncomeTax', 'trailingDeferredIncomeTax', 'annualDepreciationAndAmortization', 'trailingDepreciationAndAmortization', 'annualNetIncome', 'trailingNetIncome']

quarterly_cash_flow_referer = "https://uk.finance.yahoo.com/quote/TSLA/cash-flow"
quarterly_cash_flow_url = "https://query2.finance.yahoo.com/ws/fundamentals-timeseries/v1/finance/timeseries"
quarterly_cash_flow = ['quarterlyFreeCashFlow', 'trailingFreeCashFlow', 'quarterlyCapitalExpenditure', 'trailingCapitalExpenditure', 'quarterlyOperatingCashFlow', 'trailingOperatingCashFlow', 'quarterlyEndCashPosition', 'trailingEndCashPosition', 'quarterlyBeginningCashPosition', 'trailingBeginningCashPosition', 'quarterlyChangeInCashSupplementalAsReported', 'trailingChangeInCashSupplementalAsReported', 'quarterlyCashFlowFromContinuingFinancingActivities', 'trailingCashFlowFromContinuingFinancingActivities', 'quarterlyNetOtherFinancingCharges', 'trailingNetOtherFinancingCharges', 'quarterlyCashDividendsPaid', 'trailingCashDividendsPaid', 'quarterlyRepurchaseOfCapitalStock', 'trailingRepurchaseOfCapitalStock', 'quarterlyCommonStockIssuance', 'trailingCommonStockIssuance', 'quarterlyRepaymentOfDebt', 'trailingRepaymentOfDebt', 'quarterlyInvestingCashFlow', 'trailingInvestingCashFlow', 'quarterlyNetOtherInvestingChanges', 'trailingNetOtherInvestingChanges', 'quarterlySaleOfInvestment', 'trailingSaleOfInvestment', 'quarterlyPurchaseOfInvestment', 'trailingPurchaseOfInvestment', 'quarterlyPurchaseOfBusiness', 'trailingPurchaseOfBusiness', 'quarterlyOtherNonCashItems', 'trailingOtherNonCashItems', 'quarterlyChangeInAccountPayable', 'trailingChangeInAccountPayable', 'quarterlyChangeInInventory', 'trailingChangeInInventory', 'quarterlyChangesInAccountReceivables', 'trailingChangesInAccountReceivables', 'quarterlyChangeInWorkingCapital', 'trailingChangeInWorkingCapital', 'quarterlyStockBasedCompensation', 'trailingStockBasedCompensation', 'quarterlyDeferredIncomeTax', 'trailingDeferredIncomeTax', 'quarterlyDepreciationAndAmortization', 'trailingDepreciationAndAmortization', 'quarterlyNetIncome', 'trailingNetIncome']

annual_income_statement_referer = "https://uk.finance.yahoo.com/quote/TSLA/financials"
annual_income_statement_url = "https://query2.finance.yahoo.com/ws/fundamentals-timeseries/v1/finance/timeseries/"
annual_income_statement = ['annualEbitda', 'trailingEbitda', 'annualDilutedAverageShares', 'trailingDilutedAverageShares', 'annualBasicAverageShares', 'trailingBasicAverageShares', 'annualDilutedEPS', 'trailingDilutedEPS', 'annualBasicEPS', 'trailingBasicEPS', 'annualNetIncomeCommonStockholders', 'trailingNetIncomeCommonStockholders', 'annualNetIncome', 'trailingNetIncome', 'annualNetIncomeContinuousOperations', 'trailingNetIncomeContinuousOperations', 'annualTaxProvision', 'trailingTaxProvision', 'annualPretaxIncome', 'trailingPretaxIncome', 'annualOtherIncomeExpense', 'trailingOtherIncomeExpense', 'annualInterestExpense', 'trailingInterestExpense', 'annualOperatingIncome', 'trailingOperatingIncome', 'annualOperatingExpense', 'trailingOperatingExpense', 'annualSellingGeneralAndAdministration', 'trailingSellingGeneralAndAdministration', 'annualResearchAndDevelopment', 'trailingResearchAndDevelopment', 'annualGrossProfit', 'trailingGrossProfit', 'annualCostOfRevenue', 'trailingCostOfRevenue', 'annualTotalRevenue', 'trailingTotalRevenue']

quarterly_income_statement_referer = "https://uk.finance.yahoo.com/quote/TSLA/financials"
quarterly_income_statement = "https://query1.finance.yahoo.com/ws/fundamentals-timeseries/v1/finance/timeseries/"
quarterly_income_statement = ['quarterlyEbitda', 'trailingEbitda', 'quarterlyDilutedAverageShares', 'trailingDilutedAverageShares', 'quarterlyBasicAverageShares', 'trailingBasicAverageShares', 'quarterlyDilutedEPS', 'trailingDilutedEPS', 'quarterlyBasicEPS', 'trailingBasicEPS', 'quarterlyNetIncomeCommonStockholders', 'trailingNetIncomeCommonStockholders', 'quarterlyNetIncome', 'trailingNetIncome', 'quarterlyNetIncomeContinuousOperations', 'trailingNetIncomeContinuousOperations', 'quarterlyTaxProvision', 'trailingTaxProvision', 'quarterlyPretaxIncome', 'trailingPretaxIncome', 'quarterlyOtherIncomeExpense', 'trailingOtherIncomeExpense', 'quarterlyInterestExpense', 'trailingInterestExpense', 'quarterlyOperatingIncome', 'trailingOperatingIncome', 'quarterlyOperatingExpense', 'trailingOperatingExpense', 'quarterlySellingGeneralAndAdministration', 'trailingSellingGeneralAndAdministration', 'quarterlyResearchAndDevelopment', 'trailingResearchAndDevelopment', 'quarterlyGrossProfit', 'trailingGrossProfit', 'quarterlyCostOfRevenue', 'trailingCostOfRevenue', 'quarterlyTotalRevenue', 'trailingTotalRevenue']

analysis_base_url = "https://query1.finance.yahoo.com/v10/finance/quoteSummary/TSLA"
referer = "https://uk.finance.yahoo.com/quote/TSLA/analysis"
analysis_formatted = "true"
analysis_crumb = "45WGS5sXKp6"
analysis_modules = ['upgradeDowngradeHistory', 'recommendationTrend', 'financialData', 'earningsHistory', 'earningsTrend', 'industryTrend', 'indexTrend', 'sectorTrend']

statistics_referer = "https://uk.finance.yahoo.com/quote/TSLA/key-statistics"
statistics_base_url = "https://query2.finance.yahoo.com/ws/fundamentals-timeseries/v1/finance/timeseries/"
statistics_type = ['quarterlyMarketCap', 'trailingMarketCap', 'quarterlyEnterpriseValue', 'trailingEnterpriseValue', 'quarterlyPeRatio', 'trailingPeRatio', 'quarterlyForwardPeRatio', 'trailingForwardPeRatio', 'quarterlyPegRatio', 'trailingPegRatio', 'quarterlyPsRatio', 'trailingPsRatio', 'quarterlyPbRatio', 'trailingPbRatio', 'quarterlyEnterprisesValueRevenueRatio', 'trailingEnterprisesValueRevenueRatio', 'quarterlyEnterprisesValueEBITDARatio', 'trailingEnterprisesValueEBITDARatio']


